# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Verify that pull requests have new version

on:
  - workflow_dispatch
  - pull_request

jobs:
  ensure_new_version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify unique version
      run: if git tag --list | grep -q v$( cat VERSION ); then echo "no new version"; exit 1; else echo "new version provided"; fi
