on:
  push:
    branches:
      - master

name: Create Release

jobs:
  release:
    name: Create release and publish to pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        run:  echo "VERSION=v$( cat VERSION )" >> $GITHUB_ENV
      - name: Check if current version already exists as tag
        id: checkVersion
        uses: mukunku/tag-exists-action@v1.0.0
        with: 
          tag: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to pypi if new version
        if: ${{ steps.checkVersion.outputs.exists == 'false' }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        if: ${{ steps.checkVersion.outputs.exists == 'false' }}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        if: ${{ steps.checkVersion.outputs.exists == 'false' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

      - name: Create release if new version
        if: ${{ steps.checkVersion.outputs.exists == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MSG_SEPARATOR: |+
            ___
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body: ${{ join( github.event.commits.*.message, env.MSG_SEPARATOR ) }}
          draft: false
          prerelease: false

