on:
  push:
    branches:
      - master
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : Verify new version
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "::set-env name=SAME_VERSION::$(git tags | grep $(cat VERSION))"
          echo "${{ env.SAME_VERSION }}"
      - name: Test For now new version
        if: ${{ env.SAME_VERSION != '' }}
        run:  echo 'No new version -> no new release'
      - name: Create Release
        id: create_release
        if: ${{ false }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ join( github.event.commits.*.message, '; ') }}
          draft: false
          prerelease: false
