on:
  push:
    branches:
      - master
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : Verify new version
        run: if git tag | grep -q $( cat VERSION ); then echo "NEW_RELEASE=true" >> $GITHUB_ENV ; else echo "no match"; fi
      - name: Test For now old version
        if: ${{ env.NEW_RELEASE != 'true' }}
        run:  echo 'No new version -> no new release'
      - name: Test For now new version
        if: ${{ env.NEW_RELEASE == 'true' }}
        run:  echo 'new version -> new release'
      - name: Create Release
        id: create_release
        if: ${{ false }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ join( github.event.commits.*.message, '; ') }}
          draft: false
          prerelease: false
